### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by marsjaninzmarsa** [tymofij/adofex#56]

**Comment by tymofij** [comment]
Hello, sorry for the issue. Webfaction has moved the server to other machine, and it is now available at IP 185.20.50.109

I do not control the domain, I contacted Babelzilla people to change it, hope it will happen soon.

Meanwhile, you can add line `185.20.50.109 beta.babelzilla.org` to your /etc/hosts
Or access website as `adofex.clear.com.ua` -- this one will work in an hour.

**Comment by tymofij** [comment]
Hello, sorry for the issue. Webfaction has moved the server to other machine, and it is now available at IP 185.20.50.109

I do not control the domain, I contacted Babelzilla people to change it, hope it will happen soon.

Meanwhile, you can add line `185.20.50.109 beta.babelzilla.org` to your /etc/hosts
Or access website as `adofex.clear.com.ua`.
