### ISSUE TITLE
DISCONTINUED, BY THE END OF 2017

### ISSUE THREAD

**Issue by RealRaven2000** [tymofij/adofex#59]
Thunderbird, Pale Moon, SeaMonkey, Postbox and Waterfox will keep continuing to support XUL addons, therefore closing down this project would be counterproductive especially to the numerous mail based addons that absolutely need XPCOM to function. Also note that parts (or all) of the mozilla-central code tree will be integrateed into comm-central so Thunderbird is not planning on a dramatic loss of functionality.

I am just currently doing a lot of work on http://adofex.clear.com.ua/projects/p/smarttemplate4/ because I am pushing for a premium version of this Thunderbird addon. Are we to move (back) all translators to the much slower babelzilla.org by end of this year??

**Comment by tymofij** [comment]
I have seen email messages notifying on your plans for SmartTemplate (apparently my summer announcement about url change and discontinuation plans did not reach you) -- the project will keep on running.

**Comment by RealRaven2000** [comment]
great - I think you have a readme on the first page you may want to update, as one of my translators expressed doubt on continuing the work. ON top of code fixing I am forced to do quite a bit of damage control at the moment because of Firefox's recent changes regarding legacy add-ons and code streamlining in Gecko 57.

**Comment by tymofij** [comment]
Readme updated.
